# name of web application
webapp.name=mirotest
webapp.version=5.0.6

# name of generated war file
webapp.war=${webapp.name}.war

# error messages mail settings 
# for log4j.properties file (in web/WEB-INF/log4.properties).
error.mailTo=dev@miro-assessment.com
error.server=localhost


database.jar=${postgresql.jar}
database.type=postgresql
database.host=localhost
#database URL for creating other databases (doesn't work with pgsql)
#database.admin.url=jdbc:${database.type}://${database.host}/template1
database.admin.username=mobriz	
database.admin.password=standard
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
database.driver_class=org.postgresql.Driver