alter table app_user drop constraint FK459C57299A76B56;
alter table mr.constraints drop constraint FK63EF1B6D6AFEF2BE;
alter table mr.lookupdefitems drop constraint FKE10C19BEAF7C9776;
alter table mr.miroprojects drop constraint FKE20585FCE98BC4AA;
alter table mr.miroteam_user drop constraint FK8988972B6934AE9E;
alter table mr.miroteam_user drop constraint FK8988972B7FEF34DE;
alter table mr.options drop constraint FK69BB2F556AFEF2BE;
alter table mr.questions drop constraint FKF7298444995AF3E;
alter table mr.responses drop constraint FK4D8CB494995AF3E;
alter table mr.responses drop constraint FK4D8CB49E98BC4AA;
alter table mr.setting drop constraint FK2A93B7079A76B56;
alter table mr.survey_user drop constraint FKE705FAC74995AF3E;
alter table mr.survey_user drop constraint FKE705FAC76934AE9E;
alter table mr.surveys drop constraint FK45C5ED109A76B56;
alter table user_role drop constraint FK143BF46AC409EABE;
alter table user_role drop constraint FK143BF46A6934AE9E;
drop table app_user;
drop table mr.account;
drop table mr.constraints;
drop table mr.lookupdefitems;
drop table mr.lookupdefs;
drop table mr.miroprojects;
drop table mr.miroteam_user;
drop table mr.miroteams;
drop table mr.mirotransactions;
drop table mr.mobrizalerts;
drop table mr.options;
drop table mr.questions;
drop table mr.responses;
drop table mr.setting;
drop table mr.survey_user;
drop table mr.surveys;
drop table mr.webpages;
drop table role;
drop table user_role;
drop sequence hibernate_sequence;
create table app_user (id int8 not null, version int4 not null, user_type varchar(50), default_survey_id varchar(255), miroTeamAdded_on timestamp, department varchar(255), miroTeam_id int8, lastUpdatedBy_id int8, checkPoint int8, updated_at timestamp, createdBy_id int8, status int4, creditBalance int4, response_id int8, project_id int8, deleted bool, employeeRef varchar(255), pinNumber varchar(255), account_id int8 not null, username varchar(50) not null unique, password varchar(255) not null, first_name varchar(50) not null, last_name varchar(50) not null, email varchar(255) not null unique, password_hint varchar(255), enabled char(1), gdpr char(1), account_expired char(1) not null, account_locked char(1) not null, credentials_expired char(1) not null, phone_number varchar(255), address1 varchar(255), address2 varchar(255), city varchar(255), company varchar(255), county varchar(255), postcode varchar(255), webaddress varchar(255), created_on timestamp, oldreport bool, primary key (id));
create table mr.account (id int8 not null, companyName varchar(50) not null, primary key (id));
create table mr.constraints (id int8 not null, version int4 not null, deleted bool, CType int4, d1 timestamp, d2 timestamp, i1 int4, i2 int4, JQuestion_id int8, question_id int8, checkPoint int8, created_on timestamp, createdBy_id int8, lastUpdatedBy_id int8, updated_at timestamp, primary key (id));
create table mr.lookupdefitems (id int8 not null, lookupDef_id int8, lookup1 varchar(255), lookup2 varchar(255), lookup3 varchar(255), lookup4 varchar(255), lookup5 varchar(255), account_id int8, deleted bool, lookup6 varchar(255), lookup7 varchar(255), primary key (id));
create table mr.lookupdefs (id int8 not null, version int4 not null, account_id int8, name varchar(30) not null, description varchar(255) not null, lookupDesc1 varchar(30) not null, lookupDesc2 varchar(30) not null, lookupDesc3 varchar(30) not null, lookupDesc4 varchar(30) not null, lookupDesc5 varchar(30) not null, checkPoint int8, created_on timestamp, createdBy_id int8, lastUpdatedBy_id int8, updated_at timestamp, deleted bool, lookupDesc6 varchar(30) not null, lookupDesc7 varchar(30) not null, lookupSearch1 bool, lookupSearch2 bool, lookupSearch3 bool, lookupSearch4 bool, lookupSearch5 bool, lookupSearch6 bool, lookupSearch7 bool, lookupReport1 bool, lookupReport2 bool, lookupReport3 bool, lookupReport4 bool, lookupReport5 bool, lookupReport6 bool, lookupReport7 bool, lookupPrompt varchar(100) not null, primary key (id));
create table mr.miroprojects (id int8 not null, bcc_practitioner char(1), costcode varchar(50) not null, emailInviteSubject varchar(50) not null, emailInviteText varchar(100) not null, projectDescription varchar(254) not null, projectStatus int4, projectTitle varchar(100) not null, checkPoint int8, createdBy_id int8, created_on timestamp, lastUpdatedBy_id int8, updated_at timestamp, version int4, primary key (id));
create table mr.miroteam_user (miroteam_id int8 not null, user_id int8 not null, primary key (miroteam_id, user_id));
create table mr.miroteams (id int8 not null, commentary varchar(255), teamReportStatus int4, miroTeamName varchar(100) not null, checkPoint int8, created_on timestamp, createdBy_id int8, lastUpdatedBy_id int8, updated_at timestamp, version int4, deleted bool, primary key (id));
create table mr.mirotransactions (id int8 not null, version int4 not null, paymentStatus varchar(255), paymentStatusDetail varchar(255), paymentTransId varchar(255), transValue float8, credits int4, errorCode int4, paymentMethod int4, status int4, user_id int8, deleted bool, checkPoint int8, created_on timestamp, createdBy_id int8, lastUpdatedBy_id int8, updated_at timestamp, primary key (id));
create table mr.mobrizalerts (id int8 not null, emailAdress varchar(255), checkPoint int8, createdBy_id int8, created_on timestamp, lastUpdatedBy_id int8, updated_at timestamp, version int4, deleted bool, account_id int8, alertRules varchar(255), alertTitle varchar(100) not null, enabled bool, executionOrder int4, stopProcessing bool, emailSubject varchar(255), emailBody varchar(255), primary key (id));
create table mr.options (id int8 not null, version int4 not null, deleted bool, JQuestion_id int8, OText varchar(255), question_id int8, checkPoint int8, created_on timestamp, createdBy_id int8, lastUpdatedBy_id int8, updated_at timestamp, OType varchar(255), primary key (id));
create table mr.questions (id int8 not null, version int4 not null, branch_jquestion_id int8, shortname varchar(255), sticky bool, required bool, deleted bool, JQuestion_id int8, QTxt varchar(255), QType int4, survey_id int8, checkPoint int8, created_on timestamp, createdBy_id int8, lastUpdatedBy_id int8, updated_at timestamp, QMeta varchar(255), primary key (id));
create table mr.responses (id int8 not null, version int4 not null, answer_trail varchar(255), question_trail varchar(255), deleted bool, checkPoint int8, createdBy_id int8, lastUpdatedBy_id int8, updated_at timestamp, survey_id int8, total int4, created_on timestamp, photosStamped bool, alertsProcessed bool, primary key (id));
create table mr.setting (id int8 not null, account_id int8 not null, settingDescription varchar(255) not null, settingName varchar(30) not null, settingValue varchar(255) not null, primary key (id));
create table mr.survey_user (survey_id int8 not null, user_id int8 not null, primary key (survey_id, user_id));
create table mr.surveys (id int8 not null, photoFile varchar(255), account_id int8 not null, surveyStatus char(1), surveyVersion varchar(255), visibility int4, common bool, firstQuestion_id int8, version int4, title varchar(255), checkPoint int8, created_on timestamp, createdBy_id int8, lastUpdatedBy_id int8, updated_at timestamp, lastZipResponse_id int8, lastPhotoStampResponse_id int8, primary key (id));
create table mr.webpages (id int8 not null, pageSummary varchar(255), pageType int4, publishedDate timestamp, pageStatus int4, description varchar(255) not null, menuContextId int4, pageName varchar(255) not null, pageText varchar(255), primary key (id));
create table role (id int8 not null, name varchar(20), description varchar(64), primary key (id));
create table user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table app_user add constraint FK459C57299A76B56 foreign key (account_id) references mr.account;
alter table mr.constraints add constraint FK63EF1B6D6AFEF2BE foreign key (question_id) references mr.questions;
alter table mr.lookupdefitems add constraint FKE10C19BEAF7C9776 foreign key (lookupDef_id) references mr.lookupdefs;
alter table mr.miroprojects add constraint FKE20585FCE98BC4AA foreign key (createdBy_id) references app_user;
alter table mr.miroteam_user add constraint FK8988972B6934AE9E foreign key (user_id) references app_user;
alter table mr.miroteam_user add constraint FK8988972B7FEF34DE foreign key (miroteam_id) references mr.miroteams;
alter table mr.options add constraint FK69BB2F556AFEF2BE foreign key (question_id) references mr.questions;
alter table mr.questions add constraint FKF7298444995AF3E foreign key (survey_id) references mr.surveys;
alter table mr.responses add constraint FK4D8CB494995AF3E foreign key (survey_id) references mr.surveys;
alter table mr.responses add constraint FK4D8CB49E98BC4AA foreign key (createdBy_id) references app_user;
alter table mr.setting add constraint FK2A93B7079A76B56 foreign key (account_id) references mr.account;
alter table mr.survey_user add constraint FKE705FAC74995AF3E foreign key (survey_id) references mr.surveys;
alter table mr.survey_user add constraint FKE705FAC76934AE9E foreign key (user_id) references app_user;
alter table mr.surveys add constraint FK45C5ED109A76B56 foreign key (account_id) references mr.account;
alter table user_role add constraint FK143BF46AC409EABE foreign key (role_id) references role;
alter table user_role add constraint FK143BF46A6934AE9E foreign key (user_id) references app_user;
create sequence hibernate_sequence;
