#Hibernate Configuration for JUnit tests
#Tue, 24 Jul 2012 20:20:24 +0100

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc\:postgresql\://localhost/mirotestdb?useUnicode\=true&characterEncoding\=utf-8
hibernate.connection.username=mobriz
hibernate.connection.password=standard
hibernate.connection.show_sql=true
dao.type=hibernate
