#Hibernate Configuration for JUnit tests
#Thu, 02 Aug 2012 18:12:43 +0100

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc\:postgresql\://localhost/mirotestdb?useUnicode\=true&characterEncoding\=utf-8
hibernate.connection.username=mobriz
hibernate.connection.password=standard
hibernate.connection.show_sql=true
dao.type=hibernate
