#Hibernate Configuration for JUnit tests
#Mon, 09 Feb 2026 21:02:05 +0000

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc\:postgresql\://localhost/mirotestdb?useUnicode\=true&characterEncoding\=utf-8
hibernate.connection.username=mobriz
hibernate.connection.password=standard
hibernate.connection.show_sql=true
dao.type=hibernate
