# name of generated war file
webapp.warname=swift3
webapp.war=${webapp.warname}.war



client.version=3.0.0


#database URL for creating other databases (doesn't work with pgsql)
#database.admin.url=jdbc:${database.type}://${database.host}/template1
atabase.admin.username=mobriz	
database.admin.password=standard
database.name=swift3_mobrizdb4

