package uk.co.bluetrail.mobriz.webapp.form;

import javax.servlet.http.HttpServletRequest;


/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="constraintForm" 
 */
public class ConstraintForm
   
    implements java.io.Serializable
{

    protected boolean deleted;

    protected String version;

    protected String CType;

    protected String d1;

    protected String d2;

    protected String i1;

    protected String i2;

    protected String id;

    protected String JQuestion_id;

    protected String question_id;

    protected String created_on;

    protected String createdBy_id;

    protected String lastUpdatedBy_id;

    protected String updated_at;

    /** Default empty constructor. */
    public ConstraintForm() {}

    public boolean isDeleted()
    {
        return this.deleted;
    }
   /**
    */

    public void setDeleted( boolean deleted )
    {
        this.deleted = deleted;
    }

    public String getVersion()
    {
        return this.version;
    }
   /**
    */

    public void setVersion( String version )
    {
        this.version = version;
    }

    public String getCType()
    {
        return this.CType;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCType( String CType )
    {
        this.CType = CType;
    }

    public String getD1()
    {
        return this.d1;
    }
   /**
    */

    public void setD1( String d1 )
    {
        this.d1 = d1;
    }

    public String getD2()
    {
        return this.d2;
    }
   /**
    */

    public void setD2( String d2 )
    {
        this.d2 = d2;
    }

    public String getI1()
    {
        return this.i1;
    }
   /**
    */

    public void setI1( String i1 )
    {
        this.i1 = i1;
    }

    public String getI2()
    {
        return this.i2;
    }
   /**
    */

    public void setI2( String i2 )
    {
        this.i2 = i2;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getJQuestion_id()
    {
        return this.JQuestion_id;
    }
   /**
    */

    public void setJQuestion_id( String JQuestion_id )
    {
        this.JQuestion_id = JQuestion_id;
    }

    public String getQuestion_id()
    {
        return this.question_id;
    }
   /**
    */

    public void setQuestion_id( String question_id )
    {
        this.question_id = question_id;
    }

    public String getCreated_on()
    {
        return this.created_on;
    }
   /**
    */

    public void setCreated_on( String created_on )
    {
        this.created_on = created_on;
    }

    public String getCreatedBy_id()
    {
        return this.createdBy_id;
    }
   /**
    */

    public void setCreatedBy_id( String createdBy )
    {
        this.createdBy_id = createdBy;
    }

    public String getLastUpdatedBy_id()
    {
        return this.lastUpdatedBy_id;
    }
   /**
    */

    public void setLastUpdateBy_id( String lastUpdateBy )
    {
        this.lastUpdatedBy_id = lastUpdateBy;
    }

    public String getUpdated_at()
    {
        return this.updated_at;
    }
   /**
    */

    public void setUpdated_at( String updated_at )
    {
        this.updated_at = updated_at;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-ConstraintForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    

}
