package uk.co.bluetrail.mobriz.webapp.form;

import javax.servlet.http.HttpServletRequest;


/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="optionForm" 
 */
public class OptionForm
   
    implements java.io.Serializable
{

    protected boolean deleted;

    protected String version;

    protected String id;

    protected String JQuestion_id;

    protected String OText;

    protected String question_id;

    protected String created_on;

    protected String createdBy_id;

    protected String lastUpdatedBy_id;

    protected String updated_at;

    protected String OType;

    /** Default empty constructor. */
    public OptionForm() {}

    public boolean isDeleted()
    {
        return this.deleted;
    }
   /**
    */

    public void setDeleted( boolean deleted )
    {
        this.deleted = deleted;
    }

    public String getVersion()
    {
        return this.version;
    }
   /**
    */

    public void setVersion( String version )
    {
        this.version = version;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getJQuestion_id()
    {
        return this.JQuestion_id;
    }
   /**
    */

    public void setJQuestion_id( String JQuestion_id )
    {
        this.JQuestion_id = JQuestion_id;
    }

    public String getOText()
    {
        return this.OText;
    }
   /**
    * @struts.validator type="required"
    * @struts.validator type="maxlength" arg1value="20"
    * @struts.validator-var name="maxlength" value="20" arg1value="20"
    */

    public void setOText( String OText )
    {
        this.OText = OText;
    }

    public String getQuestion_id()
    {
        return this.question_id;
    }
   /**
    */

    public void setQuestion_id( String question_id )
    {
        this.question_id = question_id;
    }

    public String getCreated_on()
    {
        return this.created_on;
    }
   /**
    */

    public void setCreated_on( String created_on )
    {
        this.created_on = created_on;
    }

    public String getCreatedBy_id()
    {
        return this.createdBy_id;
    }
   /**
    */

    public void setCreatedBy_id( String createdBy )
    {
        this.createdBy_id = createdBy;
    }

    public String getLastUpdatedBy_id()
    {
        return this.lastUpdatedBy_id;
    }
   /**
    */

    public void setLastUpdatedBy_id( String lastUpdateBy )
    {
        this.lastUpdatedBy_id = lastUpdateBy;
    }

    public String getUpdated_at()
    {
        return this.updated_at;
    }
   /**
    */

    public void setUpdated_at( String updated_at )
    {
        this.updated_at = updated_at;
    }

    public String getOType()
    {
        return this.OType;
    }
   /**
    */

    public void setOType( String OType )
    {
        this.OType = OType;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-OptionForm.java 
           containing the additional code and place it in your metadata/web directory.
        */


}
