package uk.co.bluetrail.mobriz.webapp.form;

import javax.servlet.http.HttpServletRequest;


/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="questionForm" 
 */
public class QuestionForm
   
    implements java.io.Serializable
{

    protected String branch_jquestion_id;

    protected String shortname;

    protected boolean sticky;

    protected boolean required;

    protected boolean deleted;

    protected String version;

    protected String id;

    protected String JQuestion_id;

    protected String QTxt;

    protected String QType;

    protected String survey_id;

    protected String created_on;

    protected String createdBy_id;

    protected String lastUpdatedBy_id;

    protected String updated_at;
    
    protected String QMeta ;

    public String getQMeta() {
		return QMeta;
	}

	public void setQMeta(String meta) {
		QMeta = meta;
	}

	/** Default empty constructor. */
    public QuestionForm() {}

    public String getBranch_jquestion_id()
    {
        return this.branch_jquestion_id;
    }
   /**
    * @struts.validator type="required"
    */

    public void setBranch_jquestion_id( String branch_jquestion_id )
    {
        this.branch_jquestion_id = branch_jquestion_id;
    }

    public String getShortname()
    {
        return this.shortname;
    }
   /**
    * @struts.validator type="required"
    * @struts.validator type="maxlength" arg1value="20"
    * @struts.validator-var name="maxlength" value="20" arg1value="20"
    */

    public void setShortname( String shortname )
    {
        this.shortname = shortname;
    }

    public boolean isSticky()
    {
        return this.sticky;
    }
   /**
    */

    public void setSticky( boolean sticky )
    {
        this.sticky = sticky;
    }

    public boolean isRequired()
    {
        return this.required;
    }
   /**
    */

    public void setRequired( boolean required )
    {
        this.required = required;
    }

    public boolean isDeleted()
    {
        return this.deleted;
    }
   /**
    */

    public void setDeleted( boolean deleted )
    {
        this.deleted = deleted;
    }

    public String getVersion()
    {
        return this.version;
    }
   /**
    */

    public void setVersion( String version )
    {
        this.version = version;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getJQuestion_id()
    {
        return this.JQuestion_id;
    }
   /**
    * @struts.validator type="required"
    */

    public void setJQuestion_id( String JQuestion_id )
    {
        this.JQuestion_id = JQuestion_id;
    }

    public String getQTxt()
    {
        return this.QTxt;
    }
   /**
    * @struts.validator type="required"
    * @struts.validator type="maxlength" arg1value="100"
    * @struts.validator-var name="maxlength" value="100" arg1value="100"
    */

    public void setQTxt( String QTxt )
    {
        this.QTxt = QTxt;
    }

    public String getQType()
    {
        return this.QType;
    }
   /**
    * @struts.validator type="required"
    */

    public void setQType( String QType )
    {
        this.QType = QType;
    }

    public String getSurvey_id()
    {
        return this.survey_id;
    }
   /**
    * @struts.validator type="required"
    */

    public void setSurvey_id( String survey_id )
    {
        this.survey_id = survey_id;
    }

    public String getCreated_on()
    {
        return this.created_on;
    }
   /**
    */

    public void setCreated_on( String created_on )
    {
        this.created_on = created_on;
    }

    public String getCreatedBy_id()
    {
        return this.createdBy_id;
    }
   /**
    */

    public void setCreatedBy_id( String createdBy )
    {
        this.createdBy_id = createdBy;
    }

    public String getLastUpdateBy_id()
    {
        return this.lastUpdatedBy_id;
    }
   /**
    */

    public void setLastUpdateBy_id( String lastUpdateBy )
    {
        this.lastUpdatedBy_id = lastUpdateBy;
    }

    public String getUpdated_at()
    {
        return this.updated_at;
    }
   /**
    */

    public void setUpdated_at( String updated_at )
    {
        this.updated_at = updated_at;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-QuestionForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
   

}
