package uk.co.bluetrail.mobriz.webapp.form;

import javax.servlet.http.HttpServletRequest;


/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="surveyForm" 
 */
public class SurveyForm
    
    implements java.io.Serializable
{

    protected String surveyStatusDesc;

    protected String surveyStatus;

    protected String surveyVersion;

    protected String visibility;

    protected boolean common;

    protected transient java.util.Set users = new java.util.HashSet();

    protected String firstQuestion_id;

    protected boolean deleted;

    protected String version;

    protected String id;

    protected String title;

    protected String created_on;

    protected String createdBy_id;

    protected String lastUpdatedBy_Id;

    protected String updated_at;

    private String photoFile = null ;
    
    public String getPhotoFile() {
		return photoFile;
	}

	public void setPhotoFile(String photoFile) {
		this.photoFile = photoFile;
	}
    
    
    /** Default empty constructor. */
    public SurveyForm() {}

    public String getSurveyStatusDesc()
    {
        return this.surveyStatusDesc;
    }
   /**
    */

    public void setSurveyStatusDesc( String surveyStatusDesc )
    {
        this.surveyStatusDesc = surveyStatusDesc;
    }

    public String getSurveyStatus()
    {
        return this.surveyStatus;
    }
   /**
    */

    public void setSurveyStatus( String surveyStatus )
    {
        this.surveyStatus = surveyStatus;
    }

    public String getSurveyVersion()
    {
        return this.surveyVersion;
    }
   /**
    */

    public void setSurveyVersion( String surveyVersion )
    {
        this.surveyVersion = surveyVersion;
    }

    public String getVisibility()
    {
        return this.visibility;
    }
   /**
    */

    public void setVisibility( String visibility )
    {
        this.visibility = visibility;
    }

    public boolean isCommon()
    {
        return this.common;
    }
   /**
    */

    public void setCommon( boolean common )
    {
        this.common = common;
    }

    public java.util.Set getUsers()
    {
        return this.users;
    }
   /**
    */

    public void setUsers( java.util.Set users )
    {
        this.users = users;
    }

    public String getFirstQuestion_id()
    {
        return this.firstQuestion_id;
    }
   /**
    */

    public void setFirstQuestion_id( String firstQuestion_id )
    {
        this.firstQuestion_id = firstQuestion_id;
    }

    public boolean isDeleted()
    {
        return this.deleted;
    }
   /**
    */

    public void setDeleted( boolean deleted )
    {
        this.deleted = deleted;
    }

    public String getVersion()
    {
        return this.version;
    }
   /**
    */

    public void setVersion( String version )
    {
        this.version = version;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getTitle()
    {
        return this.title;
    }
   /**
    * @struts.validator type="required"
    * @struts.validator type="maxlength" arg1value="30"
    * @struts.validator-var name="maxlength" value="30" arg1value="30"
    */

    public void setTitle( String title )
    {
        this.title = title;
    }

    public String getCreated_on()
    {
        return this.created_on;
    }
   /**
    */

    public void setCreated_on( String created_on )
    {
        this.created_on = created_on;
    }

    public String getCreatedBy_id()
    {
        return this.createdBy_id;
    }
   /**
    */

    public void setCreatedBy_id( String createdBy )
    {
        this.createdBy_id = createdBy;
    }

    public String getLastUpdatedBy()
    {
        return this.lastUpdatedBy_Id;
    }
   /**
    */

    public void setLastUpdatedBy_id( String lastUpdateBy )
    {
        this.lastUpdatedBy_Id = lastUpdateBy;
    }

    public String getUpdated_at()
    {
        return this.updated_at;
    }
   /**
    */

    public void setUpdated_at( String updated_at )
    {
        this.updated_at = updated_at;
    }

	private String[] userNames = null ; 

	public String[] getUserNames() {
		if(userNames != null)   {
			return userNames ;
		}
    	uk.co.bluetrail.mobriz.model.User user;
        String[] userNames = new String[users.size()];
        int i = 0;
        for (java.util.Iterator iter = users.iterator(); iter.hasNext();) {
            user = (uk.co.bluetrail.mobriz.model.User) iter.next();
            userNames[i] = user.getUsername();
            i++;
        }
        return userNames;
    }

    /**
     * Note that this is not used - it's just needed by Struts.  If you look
     * in UserAction - you'll see that request.getParameterValues("userRoles")
     * is used instead.
     * 
     * @param roles
     */
    public void setUserNames(String[] userNames) {
    	this.userNames = userNames;
    }

    

}
