# This properties file is used to configure mail settings in 
# /WEB-INF/applicationContext-service.xml.

mail.default.from=miro@miro-assessment.com
mail.debug=false
mail.transport.protocol=smtp
mail.host=relay.force9.net
mail.username=
mail.password=
